apiVersion: v2
name: vsphere-csi
version: 0.1.0
description: A Helm chart for vSphere CSI Driver
appVersion: 2.2.0
home: https://github.com/kubernetes-sigs/vsphere-csi-driver
icon: https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/docs/images/vmware_logo.png
sources:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver
keywords:
  - vSphere
  - CSI
maintainers:
  - name: chogan
    email: chogan@vmware.com
  - name: Myles Gray
    email: myles@vmware.com
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x